export const API_BASE_URI = 'https://albion.neogudilap.ru'
export const API_ACCESS_TOKEN: string = process.env.API_ACCESS_TOKEN || ''
export const TOKEN: string = process.env.BOT_TOKEN || ''
export const APP_ID: string = process.env.APP_ID || ''
export const SERVER_ID: string = process.env.SERVER_ID || ''
export const FEED_UP_CHANNEL: string = process.env.FEED_UP_CHANNEL || ''
export const PASSPORT_CHANNEL: string = process.env.PASSPORT_CHANNEL || ''
export const MODERATOR_CHANNEL: string = process.env.MODERATOR_CHANNEL || ''
export const MODERATOR_USER_ID: string = process.env.MODERATOR_USER_ID || ''

export const associatedButtonCommand = 'associated'
export const sunduckButtonCommand = 'sunduck_button'
export const pingAliveRespondButtonCommand = 'ping_alive_respond'
export const buttonCommandParamSplitter = '__'
