export const API_BASE_URI = 'https://albion.gudilap.ru'
export const API_ACCESS_TOKEN: string = process.env.API_ACCESS_TOKEN || ''
export const TOKEN: string = process.env.BOT_TOKEN || ''
export const APP_ID: string = process.env.APP_ID || ''
export const SERVER_ID: string = process.env.SERVER_ID || ''
export const FEED_UP_CHANNEL: string = process.env.FEED_UP_CHANNEL || ''
export const PASSPORT_CHANNEL: string = process.env.PASSPORT_CHANNEL || ''
export const ERROR_CHANNEL: string = process.env.ERROR_CHANNEL || ''

export const associatedButtonCommand = 'associated'
export const buttonCommandParamSplitter = '__'
